import os
import subprocess
import logging
from pathlib import Path
from typing import List, Optional
from sqlalchemy.orm import Session
from .config import settings

logger = logging.getLogger("wan_api.orchestrator")

class VideoOrchestrator:
    @staticmethod
    def plan_clips(prompt: str, duration_seconds: int) -> List[str]:
        """
        Determines how many clips to generate and plans prompts for each segment.
        Supports prompt progression using semicolons:
        e.g., "A cat sleeping; A cat wakes up and looks around; A cat starts walking."
        If a single prompt is provided, it is repeated for all clips.
        """
        # Wan2.2 standard clip duration is 5 seconds
        clip_duration = 5
        total_clips = max(1, duration_seconds // clip_duration)
        
        # Split prompt by semicolon to allow narrative transitions
        prompt_segments = [p.strip() for p in prompt.split(";") if p.strip()]
        
        planned_prompts = []
        for i in range(total_clips):
            if i < len(prompt_segments):
                planned_prompts.append(prompt_segments[i])
            else:
                # Fallback to the last available prompt segment
                planned_prompts.append(prompt_segments[-1] if prompt_segments else prompt)
                
        return planned_prompts

    @staticmethod
    def stitch_clips_ffmpeg(clips: List[Path], output_path: Path) -> Path:
        """
        Losslessly stitches multiple MP4 video clips together using FFmpeg concat demuxer.
        Since all clips are generated by the same model, they share identical parameters
        (resolution, fps, codec), allowing a super-fast, lossless stream copy stitch (no re-encoding).
        """
        if not clips:
            raise ValueError("No video clips provided for stitching.")
        if len(clips) == 1:
            # Only one clip, just copy it to the final destination
            import shutil
            shutil.copy2(clips[0], output_path)
            return output_path

        # Create ffmpeg concat text file list
        concat_file = output_path.parent / f"concat_{output_path.stem}.txt"
        
        with open(concat_file, "w", encoding="utf-8") as f:
            for clip in clips:
                # Escape single quotes for ffmpeg path format
                escaped_path = str(clip.resolve()).replace("'", "'\\''")
                f.write(f"file '{escaped_path}'\n")

        try:
            # Build ffmpeg command
            # -f concat: use concat demuxer
            # -safe 0: allow absolute paths
            # -c copy: losslessly copy audio/video codecs directly without re-encoding!
            cmd = [
                settings.FFMPEG_PATH,
                "-y",
                "-f", "concat",
                "-safe", "0",
                "-i", str(concat_file),
                "-c", "copy",
                str(output_path)
            ]
            
            logger.info(f"Running FFmpeg stitch command: {' '.join(cmd)}")
            result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, check=True)
            logger.info("FFmpeg stitch completed successfully.")
            return output_path
        except subprocess.CalledProcessError as e:
            logger.error(f"FFmpeg stitching failed: {e.stderr}")
            raise RuntimeError(f"FFmpeg concatenation failed: {e.stderr}")
        finally:
            # Cleanup temporary file
            if concat_file.exists():
                os.remove(concat_file)

    @staticmethod
    def generate_single_clip_subprocess(
        clip_index: int,
        prompt: str,
        task_type: str,
        resolution: str,
        output_dir: Path,
        image_path: Optional[str] = None,
        audio_path: Optional[str] = None,
        mock_mode: bool = False
    ) -> Path:
        """
        Executes a single inference generation cycle by calling the project's 'generate.py'.
        Runs in a subprocess to protect main web server from memory leaks and PyTorch crashes.
        """
        clip_filename = f"segment_{clip_index:04d}.mp4"
        clip_path = output_dir / clip_filename
        
        # 1. Mock Mode (for local testing on systems without GPU resources)
        if mock_mode:
            import time
            logger.info(f"[MOCK] Generating clip {clip_index} with prompt: '{prompt}'...")
            time.sleep(2) # Simulate work
            
            # Use ffmpeg to generate a dummy 5-second black video with countdown text
            # This ensures that our orchestrator produces actual playable media even in mock!
            dummy_cmd = [
                settings.FFMPEG_PATH,
                "-y",
                "-f", "lavfi",
                "-i", f"color=c=black:s={ '1280x720' if resolution == '720p' else '854x480' }:d=5",
                "-vf", f"drawtext=text='Clip {clip_index+1} | Prompt: {prompt[:20]}...':fontsize=24:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2",
                "-c:v", "libx264",
                "-pix_fmt", "yuv420p",
                str(clip_path)
            ]
            try:
                subprocess.run(dummy_cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            except Exception:
                # If drawtext fails due to font config, fall back to basic color generator
                fallback_cmd = [
                    settings.FFMPEG_PATH,
                    "-y",
                    "-f", "lavfi",
                    "-i", f"color=c=blue:s=1280x720:d=5",
                    "-c:v", "libx264",
                    "-pix_fmt", "yuv420p",
                    str(clip_path)
                ]
                subprocess.run(fallback_cmd, check=True)
            return clip_path

        # 2. Real Model Inference Execution
        # Prepare parameters according to Wan2.2 codebase CLI options
        # Task mapping from request schema to generate.py tasks
        # TI2V-5B: task_type can be 'ti2v-5B' (which handles both T2V and I2V internally)
        # T2V-A14B: task_type is 't2v-A14B'
        task_param = "ti2v-5B" # Default to fast TI2V-5B model which is affordable on single GPU
        
        # Size mapping
        size_param = "1280*720" if resolution == "720p" else "854*480"
        if task_type == "ti2v" or task_param == "ti2v-5B":
            # For TI2V-5B task, 720p is explicitly 1280*704
            size_param = "1280*704" if resolution == "720p" else "854*480"

        cmd = [
            "python", str(settings.BASE_DIR / "generate.py"),
            "--task", task_param,
            "--size", size_param,
            "--ckpt_dir", str(settings.BASE_DIR / f"Wan2.2-TI2V-5B"),
            "--offload_model", "True",
            "--convert_model_dtype",
            "--t5_cpu",
            "--prompt", prompt
        ]
        
        if image_path:
            cmd.extend(["--image", str(image_path)])
        if audio_path:
            cmd.extend(["--audio", str(audio_path)])

        logger.info(f"Executing Inference Command: {' '.join(cmd)}")
        
        result = subprocess.run(
            cmd, 
            cwd=str(settings.BASE_DIR),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        
        if result.returncode != 0:
            logger.error(f"Inference process failed with exit code {result.returncode}. Stderr: {result.stderr}")
            raise RuntimeError(f"Inference failed: {result.stderr}")
            
        # The generate.py scripts by default save to a timestamped file or default folder
        # We need to find the output video file inside Wan2.2 root directory and move it to our target path.
        # Typically, generate.py outputs files like 't2v-5B_1280*704.mp4' or similar based on task config
        # Let's search for newly created mp4 files in the base directory
        possible_outputs = list(settings.BASE_DIR.glob("*.mp4"))
        if not possible_outputs:
            raise FileNotFoundError("Could not find generated video file in model workspace.")
            
        # Select the most recently modified video
        latest_video = max(possible_outputs, key=os.path.getmtime)
        
        # Move it to our clean api_storage directory
        import shutil
        shutil.move(str(latest_video), str(clip_path))
        
        return clip_path
